### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by SebastienGllmt** [bloxbean/yaci-devkit#28]
Currently users have to go to Github and download the project through the release page and put it on their computer

This is a bit tedious for my user-case (Paima) where I want people to just be able to `npm install` and be ready to go to start developing their app with Cardano

Would it be possible to have an NPM package that is just a wrapper for this package? Quite a few other projects have NPM wrappers like this for a similar reason. If you have another alternative in mind for easy version management + download for JS users I'm open to that as well, but presumably NPM works best

**Comment by satran004** [comment]
Interesting idea @SebastienGllmt . Thanks

I think we can support both zip-based and npm-based distribution. Some may still prefer zip based distribution to confirm what they are running.

I quickly checked some examples, and it seems it can be easily done. We are currently restructuring the DevKit repo to bring other components, like the CLI and viewer, into one monorepo.

We will work on this and try to push a test package asap for verification, and then we will iterate if required.

**Comment by fabianbormann** [comment]
@SebastienGllmt, that's a pretty cool idea! Also, pip/apt/brew would be possible and make sense. I guess npm has the largest Cardano user base
