### ISSUE TITLE
In the cli utxos command the option pretty-print-inline-datum is not optional

### ISSUE THREAD

**Issue by Proxiweb** [bloxbean/yaci-devkit#72]
If you don't give the --pretty-print-inline-datum value there is an error 
`Failed to convert from type [java.lang.String] to type [boolean] for value [utxos]`

**Comment by satran004** [comment]
Thanks @Proxiweb . Let me check

**Comment by Proxiweb** [comment]
The error message has disappeared. That's strange because I haven't updated the devkit... All is well now
